# This is a basic workflow to help you get started with Actions

name: Create Merge Request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Source Repository
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - with: 
          repository: source-account/source-repo
          token: ${{ secrets.SOURCE_REPO_TOKEN }}
          ref: main

      - name: Set up Git
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create New branch 
      - run: |
          git checkout -b new-branch
          # Make changes here, e.g., modify files or add new files
          echo "New changes" >> file.txt
          git add file.txt
          git commit -m "Add new changes"

      - name: Push to New Branch
        run: |
          git push origin new-branch
          
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: target-account/target-repo
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          ref: main

      - name: Create Pull Request in Target Repository
        uses: octokit/create-pull-request@v3
        with:
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          base: main
          head: new-branch
          title: "Add changes from source-repo"
          body: "This PR merges changes from the source repository."

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
